name       : python-wikipedia
version    : 1.4.0
release    : 4
source     :
    - https://pypi.python.org/packages/source/w/wikipedia/wikipedia-1.4.0.tar.gz : db0fad1829fdd441b1852306e9856398204dc0786d2996dd2e0c8bb8e26133b2
license    : MIT
component  : programming.python
summary    : Wikipedia API for Python
description: |
    Wikipedia is a Python library that makes it easy to access and parse data from Wikipedia. Search Wikipedia, get article summaries, get data like links and images from a page, and more. Wikipedia wraps the MediaWiki API so you can focus on using Wikipedia data, not getting it.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
