name       : python-wikipedia
version    : 1.4.0
release    : 1
source     :
    - https://pypi.python.org/packages/source/w/wikipedia/wikipedia-1.4.0.tar.gz : db0fad1829fdd441b1852306e9856398204dc0786d2996dd2e0c8bb8e26133b2
license    : MIT
summary    : Wikipedia API for Python
description: |
    Wikipedia is a Python library that makes it easy to access and parse data from Wikipedia. Search Wikipedia, get article summaries, get data like links and images from a page, and more. Wikipedia wraps the MediaWiki API so you can focus on using Wikipedia data, not getting it.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.4)
    - python-setuptools
    - python3-setuptools
build      : |
    for py in "python" "python3" ; do
        ${py} setup.py build
    done
install    : |
    for py in "python" "python3" ; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
